#!/bin/bash

epireg=$1
wm=$2
ctx=$3

fmdir=$(dirname $epireg)
vol=$(basename $epireg)

fslmaths $wm -edge -bin $fmdir/wm_edge
fslmaths $ctx -edge -bin $fmdir/ctx_edge

cd $fmdir
fslmaths wm_edge -add ctx_edge -bin edges

overlay 1 0 ${vol} -a ctx_edge 1 1 ${vol}_check
