#!/bin/bash

if [ $# -lt 4 ]; then
    echo "smooth_mask"
    echo "Smooth within a mask. If the mask contains multiple nonzero"
    echo "values, smoothing will be done separately for each submask."
    echo
    echo "Usage:   smooth_mask input mask fwhm output"
    echo "Example: smooth_mask loc_1.nii.gz b_ctx.nii.gz 4.0 loc_1_sm.nii.gz"
    echo
    exit 1
fi

func=$1
mask=$2
smooth=$3
output=$4

inname=$(basename $func .nii.gz)
indir=$(dirname $func)
maskname=$(basename $mask .nii.gz)
maskdir=$(dirname $mask)
outname=$(basename $output .nii.gz)
outdir=$(dirname $output)

temp=$outdir/${inname}_asm
while [ -f $outdir/$temp ]; do
    temp=$outdir/${temp}+
done

3dBlurInMask -input ${indir}/${inname}.nii.gz -FWHM $smooth -mask ${maskdir}/${maskname}.nii.gz -prefix $temp

if [ -f ${outdir}/${outname}.nii ]; then
    rm ${outdir}/${outname}.nii
fi
if [ -f ${outdir}/${outname}.nii.gz ]; then
    rm ${outdir}/${outname}.nii.gz
fi

3dAFNItoNIFTI -prefix ${outdir}/${outname} ${temp}+orig
fslmaths ${outdir}/${outname}.nii ${outdir}/${outname}.nii.gz
rm ${temp}+orig.{HEAD,BRIK} ${outdir}/${outname}.nii
