#!/usr/bin/env python

import sys

if len(sys.argv) < 2:
    print "Find subjects in one set that are not in another. Subjects"
    print "must be separated by colons within each list. Output list"
    print "will be zero-padded to two digits."
    print "Usage:   diff_subj subjs1 subjs2"
    print "Example: diff_subj 1:2:3:4 1:3"
    sys.exit()

set1 = set(sys.argv[1].split(':'))
set2 = set(sys.argv[2].split(':'))

diff = list(set1.difference(set2))
diff_number = [int(d) for d in diff]
diff_number.sort()
print ':'.join(['%d' % d for d in diff_number])

