#!/usr/bin/env python

import os
import glob
import argparse

parser = argparse.ArgumentParser(description='get_run_nos')
parser.add_argument('bold_dir', type=str)
parser.add_argument('base', type=str)
args = parser.parse_args()

# get a sorted list of run numbers
dirs = glob.glob(os.path.join(args.bold_dir, args.base + "*"))
numbers = []
for dir in dirs:
    name = os.path.basename(dir)
    snum = ""
    for c in name:
        if c.isdigit():
            snum += c
    numbers.append(int(snum))

numbers.sort()    

for n in numbers:
    print n

