#!/usr/bin/env python

import sys, os
from subprocess import call

good_files = []
for file in sys.argv[1:-1]:
    if os.path.exists(file):
        good_files.append(file)

command = 'pngappend %s %s' % (' + '.join(good_files), sys.argv[-1])
call(command.split())

