#!/bin/bash

export PSWDIR="/corral-repl/utexas/prestonlab/software"
export SWDIR="/corral-repl/utexas/poldracklab/software_lonestar"
export CORRALDIR=/corral-repl/utexas/prestonlab

export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${PSWDIR}/local/lib:${SWDIR}/lib:${SWDIR}/local/lib"

# matlab
export PATH="${PATH}:${PSWDIR}:${SWDIR}/local/bin:${SWDIR}/bin:${SWDIR}/MATLAB_R2012a/bin"

# setup python using EPD 
export PYTHONPATH="${PSWDIR}/python/lib/python2.7/site-packages:${PYTHONHOME}/lib/python2.7/site-packages/:${SWDIR}/local/openfmripipeline/src:${SWDIR}/local/lib/python:${SWDIR}/python/lib/python2.7/site-packages"
export PATH="${PATH}:${PYTHONHOME}/bin"

# FSL
export FSLDIR="${PSWDIR}/fsl"
if [ -d $FSLDIR ]; then
    . $FSLDIR/etc/fslconf/fsl.sh
    export PATH="$PATH:$FSLDIR/bin"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$FSLDIR/lib"
fi

# Freesurfer
if [ -z $FREESURFER_HOME ]; then
    export FREESURFER_HOME="${PSWDIR}/freesurfer"
fi

export PATH="${PATH}:${FREESURFER_HOME}/bin:${FREESURFER_HOME}/mni/bin"

export PERL5LIB="${PERL5LIB}:${FREESURFER_HOME}/mni/lib/perl5/5.8.5:${SWDIR}/perl/lib/perl5:${SWDIR}/perl/lib64/perl5/:${SWDIR}/perl/share/perl5/"

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${FREESURFER_HOME}/mni/lib"

export MINC_BIN_DIR="${FREESURFER_HOME}/mni/bin"
export MINC_LIB_DIR="${FREESURFER_HOME}/mni/lib"

# set up ANTS
if [ -z $ANTSHOME ]; then
    export ANTSHOME=${SWDIR}/ANTS
fi
export ANTSPATH=${ANTSHOME}/bin
export PATH=$PATH:$ANTSPATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${ANTSHOME}/lib

# DTIPrep
export DTIPREPPATH="$SWDIR/DTIPrep"
export PATH="$PATH:$DTIPREPPATH"

# set up R
if [ -z $USE_R ]; then
    export USE_R="2.13.1"
fi
if [ $USE_R == "2.15" ]; then
    export RHOME="${SWDIR}/local/lib64/R"
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${RHOME}/lib:${RHOME}/lib64"
else
    export RHOME="${SWDIR}/R-2.13.1-shlib/"
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${SWDIR}/R-2.13.1-shlib/lib64/R/lib:${SWDIR}/R-2.13.1-shlib/lib64
fi
export R_LIBS_USER="${SWDIR}/R_libs"
export PATH="$PATH:$RHOME/bin"

# java
export PATH=${PATH}:${SWDIR}/python/bin

module load python
module load hdf5
module swap intel gcc

